# 工作流名称
name: Build and Test Docker Image Locally

# 触发工作流的事件
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 定义作业
jobs:
  build-and-test:
    # 指定运行环境
    runs-on: ubuntu-latest

    # 定义步骤
    steps:
      # 步骤 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步骤 3: 构建镜像并加载到本地 Docker
      # The key change is using 'load: true' instead of 'push: true'
      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true # ✅ Loads the image to the runner's Docker daemon
          tags: jhc0000abc/pycharm2025.2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 步驟 4: 检查已加载的镜像
      # This step can now access the image because it was loaded locally
      - name: Inspect Image
        run: |
          echo "Inspecting the built image..."
          docker image inspect jhc0000abc/pycharm2025.2:latest
